INSERT INTO couriers (name, created, updated) VALUES 
('Garry Osborn', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()),
('Jhamshut', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()), 
('Nikolas', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()), 
('Muhhammajohn', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()), 
('Moloko Wenston', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()), 
('Djiabzet', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()), 
('Tomy Lee', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()), 
('Gomer Simpson', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()), 
('Bender', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()), 
('Ravshan', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()), 
('Jamshut', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP()), 
('Pete Peterson', CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP());